kapppa-joe/space-app-frontend

src/App.js, src/components/UserAuth.jsx, src/db.js
Implemented trivia and questions seperatly, added functions to set and get user's progress
=> db_functions

src/db.js
Added functions to db.js to get and set user avatar.
=> avatar functunality tested and working

src/db.js
User progress updated, now track the correctly answered questions for each spaceObject.
=> catch blocks added to functions within db.js

src/components/Onboarding.jsx
Imported getUsersByPlanet from login page to onboarding for testing.
=> getUserProgressByPlanet imported to onboarding

src/components/Login.jsx, src/components/MissionControl.jsx, src/components/Onboarding.jsx, src/db.js
Set default avatar, username, progress on sign up.
=> Mission-control

src/components/MissionControl.jsx, src/components/Onboarding.jsx, src/db.js
Changes to default values on sign-in.
=> Chnages to default user settings on log-on

package-lock.json, src/components/MissionControl.jsx, src/db.js
Further updates of mission control progress bars for each user.
=> Updated mission control progress bars, can now be updated and chenges are reflected on page.

src/App.css, src/components/MissionControl.jsx, src/db.js
Reset button, badges added to mission control.
=> Further-mission-control

src/App.js, src/components/Facts.jsx, src/db.js
Facts page is now receiving data from db and displaying facts. User must be signed in, redirect to login oage if not.
=> Facts-tests

src/components/Quiz.jsx, src/db.js
=> Quiz-db-sync

src/components/MissionControl.jsx
Added further functionality to mission control page
=> Further functunality to mission-control

package-lock.json, package.json, public/index.html, src/App.js, src/components/Acknowledgements.jsx, src/components/Finished_quiz_modal.jsx, src/components/MissionControl.jsx, src/components/Quiz.jsx, src/components/Quiz_Modal.jsx
Acknowledgements page done, mission details added to mission control.
=> Progress-bar

src/db.js
async/await added to getQuestions, getTrivia.
=> async/await added to getTrivia and GegetQuestions

src/components/Onboarding.jsx, src/components/Quiz.jsx, src/db.js
=> Bug-fixing

src/App.css, src/components/Facts.jsx, src/components/Planets.jsx, src/components/Quiz.jsx
Added different backgrounds to quiz page on correct/incorrect.
=> Quiz-design

src/App.css, src/components/Demo.jsx, src/components/Planets.jsx, src/components/Sidebar.jsx
changes:
- move Trivia / Quiz button to left & right side
- change 3D <-> AR button to toggle switch
- give some styles to demo button
- change demo modal box button color for better contrast in white background
=> change planets page button styles

src/components/Facts.jsx
Space Station component added to facts page.
=> Added SpaceStation component to facts page

src/App.css
=> Added padding to questions

src/components/Onboarding.jsx
=> fixed loading bug

public/index.html, src/App.css, src/components/Onboarding.jsx
Margin of bottom of the page fixed. Onboarding style now complete.
=> Mission-control-finish

src/components/Onboarding.jsx
Users can now submit name through enter button.
=> Users can now submit change name with enter key

src/App.css, src/App.js, src/components/SpaceStation.jsx, src/components/Trivia.jsx
Styling complete on iss live page.
=> ISS-live page styled
